dd = {"driverRequest": {"actions": [{"connectionId": "825b9f5f-b657-4406-aabc-b625e85086e7",
                                     "connectionParams": {"vlanId": "350-400", "mode": "Trunk",
                                                          "vlanServiceAttributes": [
                                                              {"attributeName": "QnQ", "attributeValue": "False",
                                                               "type": "vlanServiceAttribute"},
                                                              {"attributeName": "CTag", "attributeValue": "",
                                                               "type": "vlanServiceAttribute"},
                                                              {"attributeName": "Isolation Level",
                                                               "attributeValue": "Shared",
                                                               "type": "vlanServiceAttribute"},
                                                              {"attributeName": "Access Mode",
                                                               "attributeValue": "Trunk",
                                                               "type": "vlanServiceAttribute"},
                                                              {"attributeName": "VLAN ID", "attributeValue": "350-400",
                                                               "type": "vlanServiceAttribute"},
                                                              {"attributeName": "Pool Name", "attributeValue": "",
                                                               "type": "vlanServiceAttribute"},
                                                              {"attributeName": "Virtual Network",
                                                               "attributeValue": "350-400",
                                                               "type": "vlanServiceAttribute"}],
                                                          "type": "setVlanParameter"},
                                     "connectorAttributes": [{"attributeName": "Interface",
                                                              "attributeValue": "Juniper JunOS Switch 192.168.28.150/Chassis1/Module1/SubModule1/ge-0-0-2",
                                                              "type": "connectorAttribute"}],
                                     "actionId": "825b9f5f-b657-4406-aabc-b625e85086e7_79256485-0a74-4d8a-b933-300a1dc36889",
                                     "actionTarget": {
                                         "fullName": "Juniper JunOS Switch 192.168.28.150/Chassis1/Module1/SubModule1/ge-0-0-2",
                                         "fullAddress": "192.168.28.150/1/1/1/3", "type": "actionTarget"},
                                     "customActionAttributes": [], "type": "removeVlan"}]}}

ff = {"driverRequest": {"actions": [{"connectionId": "33cba118-ed22-4b5e-a1d7-62f43184acdc",
                                     "connectionParams": {"vlanId": "350-400", "mode": "Trunk",
                                                          "vlanServiceAttributes": [
                                                              {"attributeName": "QnQ", "attributeValue": "False",
                                                               "type": "vlanServiceAttribute"},
                                                              {"attributeName": "CTag", "attributeValue": "",
                                                               "type": "vlanServiceAttribute"},
                                                              {"attributeName": "Isolation Level",
                                                               "attributeValue": "Shared",
                                                               "type": "vlanServiceAttribute"},
                                                              {"attributeName": "Access Mode",
                                                               "attributeValue": "Trunk",
                                                               "type": "vlanServiceAttribute"},
                                                              {"attributeName": "VLAN ID", "attributeValue": "350-400",
                                                               "type": "vlanServiceAttribute"},
                                                              {"attributeName": "Pool Name", "attributeValue": "",
                                                               "type": "vlanServiceAttribute"},
                                                              {"attributeName": "Virtual Network",
                                                               "attributeValue": "350-400",
                                                               "type": "vlanServiceAttribute"}],
                                                          "type": "setVlanParameter"}, "connectorAttributes": [],
                                     "actionId": "33cba118-ed22-4b5e-a1d7-62f43184acdc_09ae4a41-1c5a-467f-9835-bba7c84d6b7a",
                                     "actionTarget": {"fullName": "Juniper JunOS Switch 192.168.28.150/ae0",
                                                      "fullAddress": "192.168.28.150/PC0", "type": "actionTarget"},
                                     "customActionAttributes": [], "type": "setVlan"}]}}
