dd = [('1.1.0.0', {'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxMidplaneMX960', 'jnxContentsInstalled': '0',
                   'suffix': '1.1.0.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '0',
                   'jnxContentsChassisCleiCode': u'COMTN00BRB', 'jnxContentsChassisDescr': u'Single Chassis',
                   'jnxContentsPartNo': u'710-030012', 'jnxContentsRevision': u'REV 01', 'jnxContentsL1Index': '1',
                   'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAW7172',
                   'jnxContentsDescr': u'midplane', 'jnxContentsContainerIndex': '1'}), ('2.1.0.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPower', 'jnxContentsInstalled': '0', 'suffix': '2.1.0.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '0', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-029344', 'jnxContentsRevision': u'Rev 07',
    'jnxContentsL1Index': '1', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'QCS1642V031',
    'jnxContentsDescr': u'PEM 0', 'jnxContentsContainerIndex': '2'}),
      ('2.2.0.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPower', 'jnxContentsInstalled': '0', 'suffix': '2.2.0.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '0', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-029344', 'jnxContentsRevision': u'Rev 07',
    'jnxContentsL1Index': '2', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'QCS1642V00K',
    'jnxContentsDescr': u'PEM 1', 'jnxContentsContainerIndex': '2'}),
      ('2.3.0.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPower', 'jnxContentsInstalled': '0', 'suffix': '2.3.0.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '0', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-029344', 'jnxContentsRevision': u'Rev 07',
    'jnxContentsL1Index': '3', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'QCS1637V06L',
    'jnxContentsDescr': u'PEM 2', 'jnxContentsContainerIndex': '2'}),
      ('2.4.0.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPower', 'jnxContentsInstalled': '0', 'suffix': '2.4.0.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '0', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-029344', 'jnxContentsRevision': u'Rev 07',
    'jnxContentsL1Index': '4', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'QCS1642V07U',
    'jnxContentsDescr': u'PEM 3', 'jnxContentsContainerIndex': '2'}),
      ('2.5.0.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPower', 'jnxContentsInstalled': '0', 'suffix': '2.5.0.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '0', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-013110', 'jnxContentsRevision': u'Rev 03',
    'jnxContentsL1Index': '5', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'QCS16105088',
    'jnxContentsDescr': u'PDM', 'jnxContentsContainerIndex': '2'}),
      ('4.1.0.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.1.0.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '0', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '1', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF2021',
    'jnxContentsDescr': u'Top Fan Tray', 'jnxContentsContainerIndex': '4'}),
      ('4.1.1.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.1.1.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '1', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '1', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF2021',
    'jnxContentsDescr': u'Top Tray Fan 1', 'jnxContentsContainerIndex': '4'}),
      ('4.1.2.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.1.2.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '2', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '1', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF2021',
    'jnxContentsDescr': u'Top Tray Fan 2', 'jnxContentsContainerIndex': '4'}),
      ('4.1.3.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.1.3.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '3', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '1', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF2021',
    'jnxContentsDescr': u'Top Tray Fan 3', 'jnxContentsContainerIndex': '4'}),
      ('4.1.4.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.1.4.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '4', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '1', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF2021',
    'jnxContentsDescr': u'Top Tray Fan 4', 'jnxContentsContainerIndex': '4'}),
      ('4.1.5.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.1.5.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '5', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '1', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF2021',
    'jnxContentsDescr': u'Top Tray Fan 5', 'jnxContentsContainerIndex': '4'}),
      ('4.1.6.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.1.6.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '6', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '1', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF2021',
    'jnxContentsDescr': u'Top Tray Fan 6', 'jnxContentsContainerIndex': '4'}),
      ('4.1.7.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.1.7.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '7', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '1', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF2021',
    'jnxContentsDescr': u'Top Tray Fan 7', 'jnxContentsContainerIndex': '4'}),
      ('4.1.8.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.1.8.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '8', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '1', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF2021',
    'jnxContentsDescr': u'Top Tray Fan 8', 'jnxContentsContainerIndex': '4'}),
      ('4.1.9.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.1.9.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '9', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '1', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF2021',
    'jnxContentsDescr': u'Top Tray Fan 9', 'jnxContentsContainerIndex': '4'}),
      ('4.1.10.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.1.10.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '10', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '1', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF2021',
    'jnxContentsDescr': u'Top Tray Fan 10', 'jnxContentsContainerIndex': '4'}),
      ('4.1.11.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.1.11.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '11', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '1', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF2021',
    'jnxContentsDescr': u'Top Tray Fan 11', 'jnxContentsContainerIndex': '4'}),
      ('4.1.12.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.1.12.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '12', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '1', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF2021',
    'jnxContentsDescr': u'Top Tray Fan 12', 'jnxContentsContainerIndex': '4'}),
      ('4.2.0.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.2.0.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '0', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '2', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF1662',
    'jnxContentsDescr': u'Bottom Fan Tray', 'jnxContentsContainerIndex': '4'}),
      ('4.2.1.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.2.1.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '1', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '2', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF1662',
    'jnxContentsDescr': u'Bottom Tray Fan 1', 'jnxContentsContainerIndex': '4'}),
      ('4.2.2.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.2.2.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '2', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '2', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF1662',
    'jnxContentsDescr': u'Bottom Tray Fan 2', 'jnxContentsContainerIndex': '4'}),
      ('4.2.3.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.2.3.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '3', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '2', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF1662',
    'jnxContentsDescr': u'Bottom Tray Fan 3', 'jnxContentsContainerIndex': '4'}),
      ('4.2.4.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.2.4.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '4', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '2', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF1662',
    'jnxContentsDescr': u'Bottom Tray Fan 4', 'jnxContentsContainerIndex': '4'}),
      ('4.2.5.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.2.5.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '5', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '2', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF1662',
    'jnxContentsDescr': u'Bottom Tray Fan 5', 'jnxContentsContainerIndex': '4'}),
      ('4.2.6.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.2.6.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '6', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '2', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF1662',
    'jnxContentsDescr': u'Bottom Tray Fan 6', 'jnxContentsContainerIndex': '4'}),
      ('4.2.7.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.2.7.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '7', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '2', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF1662',
    'jnxContentsDescr': u'Bottom Tray Fan 7', 'jnxContentsContainerIndex': '4'}),
      ('4.2.8.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.2.8.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '8', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '2', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF1662',
    'jnxContentsDescr': u'Bottom Tray Fan 8', 'jnxContentsContainerIndex': '4'}),
      ('4.2.9.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.2.9.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '9', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '2', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF1662',
    'jnxContentsDescr': u'Bottom Tray Fan 9', 'jnxContentsContainerIndex': '4'}),
      ('4.2.10.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.2.10.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '10', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '2', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF1662',
    'jnxContentsDescr': u'Bottom Tray Fan 10', 'jnxContentsContainerIndex': '4'}),
      ('4.2.11.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.2.11.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '11', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '2', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF1662',
    'jnxContentsDescr': u'Bottom Tray Fan 11', 'jnxContentsContainerIndex': '4'}),
      ('4.2.12.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsInstalled': '0', 'suffix': '4.2.12.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '12', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031521', 'jnxContentsRevision': u'REV 08',
    'jnxContentsL1Index': '2', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N ACAF1662',
    'jnxContentsDescr': u'Bottom Tray Fan 12', 'jnxContentsContainerIndex': '4'}),
      ('7.5.0.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFPC', 'jnxContentsInstalled': '3036097251', 'suffix': '7.5.0.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '0', 'jnxContentsChassisCleiCode': u'COUIBBGBAA',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'750-044444', 'jnxContentsRevision': u'REV 05',
    'jnxContentsL1Index': '5', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N CAAM2711',
    'jnxContentsDescr': u'FPC: MPCE Type 2 3D P @ 4/*/*', 'jnxContentsContainerIndex': '7'}),
      ('7.6.0.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFPC', 'jnxContentsInstalled': '3036106860', 'suffix': '7.6.0.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '0', 'jnxContentsChassisCleiCode': u'COUIBBGBAA',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'750-044444', 'jnxContentsRevision': u'REV 05',
    'jnxContentsL1Index': '6', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N CAAN6225',
    'jnxContentsDescr': u'FPC: MPCE Type 2 3D P @ 5/*/*', 'jnxContentsContainerIndex': '7'}),
      ('7.8.0.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFPC', 'jnxContentsInstalled': '3105907618', 'suffix': '7.8.0.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '0', 'jnxContentsChassisCleiCode': u'COUIBEUBAA',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'750-044444', 'jnxContentsRevision': u'REV 13',
    'jnxContentsL1Index': '8', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N CADX4483',
    'jnxContentsDescr': u'FPC: MPCE Type 2 3D P @ 7/*/*', 'jnxContentsContainerIndex': '7'}),
      ('7.10.0.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFPC', 'jnxContentsInstalled': '3105909883',
    'suffix': '7.10.0.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '0',
    'jnxContentsChassisCleiCode': u'COUIBA2BAB', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'750-038489', 'jnxContentsRevision': u'REV 10', 'jnxContentsL1Index': '10',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N CAAV3448',
    'jnxContentsDescr': u'FPC: MPCE Type 1 3D @ 9/*/*', 'jnxContentsContainerIndex': '7'}),
      ('7.11.0.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFPC', 'jnxContentsInstalled': '3105906561',
    'suffix': '7.11.0.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '0',
    'jnxContentsChassisCleiCode': u'COUIBA2BAB', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'750-038489', 'jnxContentsRevision': u'REV 10', 'jnxContentsL1Index': '11',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N CAAR5278',
    'jnxContentsDescr': u'FPC: MPCE Type 1 3D @ 10/*/*', 'jnxContentsContainerIndex': '7'}),
      ('8.5.1.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMICH10XGESFP', 'jnxContentsInstalled': '3036111001',
    'suffix': '8.5.1.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '1',
    'jnxContentsChassisCleiCode': u'COUIA15BAA', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'BUILTIN', 'jnxContentsRevision': u'REV 26', 'jnxContentsL1Index': '5',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'BUILTIN',
    'jnxContentsDescr': u'PIC: 10x 1GE(LAN) SFP @ 4/0/*', 'jnxContentsContainerIndex': '8'}),
      ('8.5.2.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMICH10XGESFP', 'jnxContentsInstalled': '3036111534',
    'suffix': '8.5.2.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '2',
    'jnxContentsChassisCleiCode': u'COUIA15BAA', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'BUILTIN', 'jnxContentsRevision': u'REV 26', 'jnxContentsL1Index': '5',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'BUILTIN',
    'jnxContentsDescr': u'PIC: 10x 1GE(LAN) SFP @ 4/1/*', 'jnxContentsContainerIndex': '8'}),
      ('8.5.3.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMICH10XGESFP', 'jnxContentsInstalled': '3036111546',
    'suffix': '8.5.3.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '3',
    'jnxContentsChassisCleiCode': u'COUIA15BAA', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'BUILTIN', 'jnxContentsRevision': u'REV 26', 'jnxContentsL1Index': '5',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'BUILTIN',
    'jnxContentsDescr': u'PIC: 10x 1GE(LAN) SFP @ 4/2/*', 'jnxContentsContainerIndex': '8'}),
      ('8.5.4.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMICH10XGESFP', 'jnxContentsInstalled': '3036112154',
    'suffix': '8.5.4.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '4',
    'jnxContentsChassisCleiCode': u'COUIA15BAA', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'BUILTIN', 'jnxContentsRevision': u'REV 26', 'jnxContentsL1Index': '5',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'BUILTIN',
    'jnxContentsDescr': u'PIC: 10x 1GE(LAN) SFP @ 4/3/*', 'jnxContentsContainerIndex': '8'}),
      ('8.6.1.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMICH10XGESFP', 'jnxContentsInstalled': '3036123249',
    'suffix': '8.6.1.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '1',
    'jnxContentsChassisCleiCode': u'COUIA15BAA', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'BUILTIN', 'jnxContentsRevision': u'REV 26', 'jnxContentsL1Index': '6',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'BUILTIN',
    'jnxContentsDescr': u'PIC: 10x 1GE(LAN) SFP @ 5/0/*', 'jnxContentsContainerIndex': '8'}),
      ('8.6.2.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMICH10XGESFP', 'jnxContentsInstalled': '3036123826',
    'suffix': '8.6.2.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '2',
    'jnxContentsChassisCleiCode': u'COUIA15BAA', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'BUILTIN', 'jnxContentsRevision': u'REV 26', 'jnxContentsL1Index': '6',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'BUILTIN',
    'jnxContentsDescr': u'PIC: 10x 1GE(LAN) SFP @ 5/1/*', 'jnxContentsContainerIndex': '8'}),
      ('8.6.3.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMICH10XGESFP', 'jnxContentsInstalled': '3036123841',
    'suffix': '8.6.3.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '3',
    'jnxContentsChassisCleiCode': u'COUIBCRBAA', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'BUILTIN', 'jnxContentsRevision': u'REV 30', 'jnxContentsL1Index': '6',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'BUILTIN',
    'jnxContentsDescr': u'PIC: 10x 1GE(LAN) SFP @ 5/2/*', 'jnxContentsContainerIndex': '8'}),
      ('8.6.4.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMICH10XGESFP', 'jnxContentsInstalled': '3036124351',
    'suffix': '8.6.4.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '4',
    'jnxContentsChassisCleiCode': u'COUIBCRBAA', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'BUILTIN', 'jnxContentsRevision': u'REV 30', 'jnxContentsL1Index': '6',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'BUILTIN',
    'jnxContentsDescr': u'PIC: 10x 1GE(LAN) SFP @ 5/3/*', 'jnxContentsContainerIndex': '8'}),
      ('8.8.1.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMICH10XGESFP', 'jnxContentsInstalled': '3105919873',
    'suffix': '8.8.1.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '1',
    'jnxContentsChassisCleiCode': u'COUIBCRBAA', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'BUILTIN', 'jnxContentsRevision': u'REV 30', 'jnxContentsL1Index': '8',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'BUILTIN',
    'jnxContentsDescr': u'PIC: 10x 1GE(LAN) SFP @ 7/0/*', 'jnxContentsContainerIndex': '8'}),
      ('8.8.2.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMICH10XGESFP', 'jnxContentsInstalled': '3105920429',
    'suffix': '8.8.2.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '2',
    'jnxContentsChassisCleiCode': u'COUIBCRBAA', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'BUILTIN', 'jnxContentsRevision': u'REV 30', 'jnxContentsL1Index': '8',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'BUILTIN',
    'jnxContentsDescr': u'PIC: 10x 1GE(LAN) SFP @ 7/1/*', 'jnxContentsContainerIndex': '8'}),
      ('8.8.3.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMICH2X10GEXFP', 'jnxContentsInstalled': '3105920446',
    'suffix': '8.8.3.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '3',
    'jnxContentsChassisCleiCode': u'COUIA16BAB', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'BUILTIN', 'jnxContentsRevision': u'REV 31', 'jnxContentsL1Index': '8',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'BUILTIN',
    'jnxContentsDescr': u'PIC: 2x 10GE  XFP @ 7/2/*', 'jnxContentsContainerIndex': '8'}),
      ('8.8.4.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMICH2X10GEXFP', 'jnxContentsInstalled': '3105920551',
    'suffix': '8.8.4.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '4',
    'jnxContentsChassisCleiCode': u'COUIA16BAB', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'BUILTIN', 'jnxContentsRevision': u'REV 31', 'jnxContentsL1Index': '8',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'BUILTIN',
    'jnxContentsDescr': u'PIC: 2x 10GE  XFP @ 7/3/*', 'jnxContentsContainerIndex': '8'}),
      ('8.10.1.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMICH1X10GEXFP', 'jnxContentsInstalled': '3105915723',
    'suffix': '8.10.1.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '1',
    'jnxContentsChassisCleiCode': u'COUIA19BAB', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'BUILTIN', 'jnxContentsRevision': u'REV 21', 'jnxContentsL1Index': '10',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'BUILTIN',
    'jnxContentsDescr': u'PIC: 1x 10GE XFP @ 9/0/*', 'jnxContentsContainerIndex': '8'}),
      ('8.10.2.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMICH1X10GEXFP', 'jnxContentsInstalled': '3105916124',
    'suffix': '8.10.2.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '2',
    'jnxContentsChassisCleiCode': u'COUIA19BAB', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'BUILTIN', 'jnxContentsRevision': u'REV 21', 'jnxContentsL1Index': '10',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'BUILTIN',
    'jnxContentsDescr': u'PIC: 1x 10GE XFP @ 9/1/*', 'jnxContentsContainerIndex': '8'}),
      ('8.11.1.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMICH1X10GEXFP', 'jnxContentsInstalled': '3105912522',
    'suffix': '8.11.1.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '1',
    'jnxContentsChassisCleiCode': u'COUIA19BAB', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'BUILTIN', 'jnxContentsRevision': u'REV 21', 'jnxContentsL1Index': '11',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'BUILTIN',
    'jnxContentsDescr': u'PIC: 1x 10GE XFP @ 10/0/*', 'jnxContentsContainerIndex': '8'}),
      ('8.11.2.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMICH1X10GEXFP', 'jnxContentsInstalled': '3105912923',
    'suffix': '8.11.2.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '2',
    'jnxContentsChassisCleiCode': u'COUIA19BAB', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'BUILTIN', 'jnxContentsRevision': u'REV 21', 'jnxContentsL1Index': '11',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'BUILTIN',
    'jnxContentsDescr': u'PIC: 1x 10GE XFP @ 10/1/*', 'jnxContentsContainerIndex': '8'}),
      ('9.1.0.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxHM', 'jnxContentsInstalled': '0', 'suffix': '9.1.0.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '0', 'jnxContentsChassisCleiCode': u'COUCALDBAB',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031116', 'jnxContentsRevision': u'REV 07',
    'jnxContentsL1Index': '1', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'9009117104',
    'jnxContentsDescr': u'Routing Engine 0', 'jnxContentsContainerIndex': '9'}),
      ('9.2.0.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxHM', 'jnxContentsInstalled': '7575', 'suffix': '9.2.0.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '0', 'jnxContentsChassisCleiCode': u'COUCALDBAB',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'740-031116', 'jnxContentsRevision': u'REV 07',
    'jnxContentsL1Index': '2', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'9009117146',
    'jnxContentsDescr': u'Routing Engine 1', 'jnxContentsContainerIndex': '9'}),
      ('10.1.1.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFPB', 'jnxContentsInstalled': '0', 'suffix': '10.1.1.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '1', 'jnxContentsChassisCleiCode': '',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'710-014974', 'jnxContentsRevision': u'REV 03',
    'jnxContentsL1Index': '1', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N CAAN9537',
    'jnxContentsDescr': u'FPM Board', 'jnxContentsContainerIndex': '10'}), ('12.1.0.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxCBD', 'jnxContentsInstalled': '0', 'suffix': '12.1.0.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '0', 'jnxContentsChassisCleiCode': u'COUCARCBAA',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'750-031391', 'jnxContentsRevision': u'REV 15',
    'jnxContentsL1Index': '1', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N CAAR0939',
    'jnxContentsDescr': u'CB 0', 'jnxContentsContainerIndex': '12'}), ('12.2.0.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxCBD', 'jnxContentsInstalled': '0', 'suffix': '12.2.0.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '0', 'jnxContentsChassisCleiCode': u'COUCARCBAA',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'750-031391', 'jnxContentsRevision': u'REV 15',
    'jnxContentsL1Index': '2', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N CAAL8282',
    'jnxContentsDescr': u'CB 1', 'jnxContentsContainerIndex': '12'}), ('12.3.0.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxCBD', 'jnxContentsInstalled': '0', 'suffix': '12.3.0.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '0', 'jnxContentsChassisCleiCode': u'COUCARCBAA',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'750-031391', 'jnxContentsRevision': u'REV 15',
    'jnxContentsL1Index': '3', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N CAAL8210',
    'jnxContentsDescr': u'CB 2', 'jnxContentsContainerIndex': '12'}), ('20.5.1.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMIC20XGESFP', 'jnxContentsInstalled': '3036111540',
    'suffix': '20.5.1.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '1',
    'jnxContentsChassisCleiCode': u'COUIA15BAA', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'750-028392', 'jnxContentsRevision': u'REV 26', 'jnxContentsL1Index': '5',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N CAAS5075',
    'jnxContentsDescr': u'MIC: 3D 20x 1GE(LAN) SFP @ 4/0/*', 'jnxContentsContainerIndex': '20'}), ('20.5.2.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMIC20XGESFP', 'jnxContentsInstalled': '3036112156',
    'suffix': '20.5.2.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '2',
    'jnxContentsChassisCleiCode': u'COUIA15BAA', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'750-028392', 'jnxContentsRevision': u'REV 26', 'jnxContentsL1Index': '5',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N CAAP0493',
    'jnxContentsDescr': u'MIC: 3D 20x 1GE(LAN) SFP @ 4/1/*', 'jnxContentsContainerIndex': '20'}), ('20.6.1.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMIC20XGESFP', 'jnxContentsInstalled': '3036123829',
    'suffix': '20.6.1.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '1',
    'jnxContentsChassisCleiCode': u'COUIA15BAA', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'750-028392', 'jnxContentsRevision': u'REV 26', 'jnxContentsL1Index': '6',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N CAAP0323',
    'jnxContentsDescr': u'MIC: 3D 20x 1GE(LAN) SFP @ 5/0/*', 'jnxContentsContainerIndex': '20'}), ('20.6.2.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMIC20XGESFP', 'jnxContentsInstalled': '3036124354',
    'suffix': '20.6.2.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '2',
    'jnxContentsChassisCleiCode': u'COUIBCRBAA', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'750-028392', 'jnxContentsRevision': u'REV 30', 'jnxContentsL1Index': '6',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N CADM4149',
    'jnxContentsDescr': u'MIC: 3D 20x 1GE(LAN) SFP @ 5/1/*', 'jnxContentsContainerIndex': '20'}), ('20.8.1.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMIC20XGESFP', 'jnxContentsInstalled': '3105920434',
    'suffix': '20.8.1.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '1',
    'jnxContentsChassisCleiCode': u'COUIBCRBAA', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'750-028392', 'jnxContentsRevision': u'REV 30', 'jnxContentsL1Index': '8',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N CADZ8933',
    'jnxContentsDescr': u'MIC: 3D 20x 1GE(LAN) SFP @ 7/0/*', 'jnxContentsContainerIndex': '20'}), ('20.8.2.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMIC4X10GEXFP', 'jnxContentsInstalled': '3105920551',
    'suffix': '20.8.2.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '2',
    'jnxContentsChassisCleiCode': u'COUIA16BAB', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'750-028387', 'jnxContentsRevision': u'REV 31', 'jnxContentsL1Index': '8',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N CADZ4751',
    'jnxContentsDescr': u'MIC: 3D 4x 10GE  XFP @ 7/1/*', 'jnxContentsContainerIndex': '20'}), ('20.10.1.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMIC2X10GEXFP', 'jnxContentsInstalled': '3105916125',
    'suffix': '20.10.1.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '1',
    'jnxContentsChassisCleiCode': u'COUIA19BAB', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'750-028380', 'jnxContentsRevision': u'REV 21', 'jnxContentsL1Index': '10',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N CAAP1133',
    'jnxContentsDescr': u'MIC: 3D 2x 10GE XFP @ 9/0/*', 'jnxContentsContainerIndex': '20'}), ('20.11.1.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPicMIC2X10GEXFP', 'jnxContentsInstalled': '3105912924',
    'suffix': '20.11.1.0', 'jnxContentsL3Index': '0', 'jnxContentsL2Index': '1',
    'jnxContentsChassisCleiCode': u'COUIA19BAB', 'jnxContentsChassisDescr': u'Single Chassis',
    'jnxContentsPartNo': u'750-028380', 'jnxContentsRevision': u'REV 21', 'jnxContentsL1Index': '11',
    'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N CAAP1062',
    'jnxContentsDescr': u'MIC: 3D 2x 10GE XFP @ 10/0/*', 'jnxContentsContainerIndex': '20'}), ('20.11.2.0', {
    'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPic.316', 'jnxContentsInstalled': '0', 'suffix': '20.11.2.0',
    'jnxContentsL3Index': '0', 'jnxContentsL2Index': '2', 'jnxContentsChassisCleiCode': u'COUIBC4BAA',
    'jnxContentsChassisDescr': u'Single Chassis', 'jnxContentsPartNo': u'750-043688', 'jnxContentsRevision': u'REV 18',
    'jnxContentsL1Index': '11', 'jnxContentsChassisId': "'singleChassis'", 'jnxContentsSerialNo': u'S/N CADT9432',
    'jnxContentsDescr': u'MIC: MS-MIC-16G @ 10/1/*', 'jnxContentsContainerIndex': '20'})]
