CONTAINER_TABLE = [(1,
                    {'jnxContainersWithin': '0', 'jnxContainersType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxChassisSRX220.0',
                     'jnxContainersCount': '1', 'jnxContainersIndex': '1', 'jnxContainersDescr': 'chassis frame',
                     'jnxContainersLevel': '0', 'jnxContainersView': '1', 'suffix': '1'}), (2,
                                                                                            {'jnxContainersWithin': '1',
                                                                                             'jnxContainersType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxSRX220SlotPower.0',
                                                                                             'jnxContainersCount': '1',
                                                                                             'jnxContainersIndex': '2',
                                                                                             'jnxContainersDescr': 'PEM slot',
                                                                                             'jnxContainersLevel': '1',
                                                                                             'jnxContainersView': '2',
                                                                                             'suffix': '2'}), (4, {
    'jnxContainersWithin': '1', 'jnxContainersType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxSRX220SlotFan.0',
    'jnxContainersCount': '1', 'jnxContainersIndex': '4', 'jnxContainersDescr': 'FAN slot', 'jnxContainersLevel': '1',
    'jnxContainersView': '2', 'suffix': '4'}), (7, {'jnxContainersWithin': '1',
                                                    'jnxContainersType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxSRX220SlotFPC.0',
                                                    'jnxContainersCount': '3', 'jnxContainersIndex': '7',
                                                    'jnxContainersDescr': 'FPC slot', 'jnxContainersLevel': '1',
                                                    'jnxContainersView': '1', 'suffix': '7'}), (8, {
    'jnxContainersWithin': '7', 'jnxContainersType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxSRX220MediaCardSpacePIC.0',
    'jnxContainersCount': '1', 'jnxContainersIndex': '8', 'jnxContainersDescr': 'PIC slot', 'jnxContainersLevel': '2',
    'jnxContainersView': '1', 'suffix': '8'}), (9, {'jnxContainersWithin': '1',
                                                    'jnxContainersType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxSRX220SlotRE.0',
                                                    'jnxContainersCount': '1', 'jnxContainersIndex': '9',
                                                    'jnxContainersDescr': 'Routing Engine slot',
                                                    'jnxContainersLevel': '1', 'jnxContainersView': '1',
                                                    'suffix': '9'})]
CONTENTS_TABLE = [('1.1.0.0', {'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxMidplaneSRX220.0',
                               'jnxContentsRevision': 'REV 18', 'jnxContentsInstalled': '0', 'suffix': '1.1.0.0',
                               'jnxContentsChassisCleiCode': '', 'jnxContentsL3Index': '0',
                               'jnxContentsDescr': 'midplane', 'jnxContentsL1Index': '1',
                               'jnxContentsSerialNo': 'AACZ0400', 'jnxContentsL2Index': '0',
                               'jnxContentsChassisId': "'singleChassis'", 'jnxContentsContainerIndex': '1',
                               'jnxContentsChassisDescr': 'Single Chassis', 'jnxContentsPartNo': '750-031177'}),
                  ('2.1.0.0', {'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPower', 'jnxContentsRevision': '',
                               'jnxContentsInstalled': '0', 'suffix': '2.1.0.0', 'jnxContentsChassisCleiCode': '',
                               'jnxContentsL3Index': '0', 'jnxContentsDescr': 'PEM 0', 'jnxContentsL1Index': '1',
                               'jnxContentsSerialNo': '', 'jnxContentsL2Index': '0',
                               'jnxContentsChassisId': "'singleChassis'", 'jnxContentsContainerIndex': '2',
                               'jnxContentsChassisDescr': 'Single Chassis', 'jnxContentsPartNo': ''}),
                  ('4.1.0.0', {
                      'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFan', 'jnxContentsRevision': '',
                      'jnxContentsInstalled': '0',
                      'suffix': '4.1.0.0', 'jnxContentsChassisCleiCode': '', 'jnxContentsL3Index': '0',
                      'jnxContentsDescr': 'SRX220 Chassis fan 0', 'jnxContentsL1Index': '1', 'jnxContentsSerialNo': '',
                      'jnxContentsL2Index': '0', 'jnxContentsChassisId': "'singleChassis'",
                      'jnxContentsContainerIndex': '4',
                      'jnxContentsChassisDescr': 'Single Chassis', 'jnxContentsPartNo': ''}),
                  ('7.1.0.0', {
                      'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxFPC', 'jnxContentsRevision': '',
                      'jnxContentsInstalled': '5839',
                      'suffix': '7.1.0.0', 'jnxContentsChassisCleiCode': '', 'jnxContentsL3Index': '0',
                      'jnxContentsDescr': 'FPC: FPC @ 0/*/*', 'jnxContentsL1Index': '1', 'jnxContentsSerialNo': '',
                      'jnxContentsL2Index': '0', 'jnxContentsChassisId': "'singleChassis'",
                      'jnxContentsContainerIndex': '7',
                      'jnxContentsChassisDescr': 'Single Chassis', 'jnxContentsPartNo': ''}),
                  ('8.1.1.0', {
                      'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxPic', 'jnxContentsRevision': '',
                      'jnxContentsInstalled': '5923',
                      'suffix': '8.1.1.0', 'jnxContentsChassisCleiCode': '', 'jnxContentsL3Index': '0',
                      'jnxContentsDescr': 'PIC: 8x GE Base PIC @ 0/0/*', 'jnxContentsL1Index': '1',
                      'jnxContentsSerialNo': '',
                      'jnxContentsL2Index': '1', 'jnxContentsChassisId': "'singleChassis'",
                      'jnxContentsContainerIndex': '8',
                      'jnxContentsChassisDescr': 'Single Chassis', 'jnxContentsPartNo': ''}),
                  ('9.1.0.0', {
                      'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxSRX220RE.0', 'jnxContentsRevision': 'REV 18',
                      'jnxContentsInstalled': '0', 'suffix': '9.1.0.0', 'jnxContentsChassisCleiCode': '',
                      'jnxContentsL3Index': '0',
                      'jnxContentsDescr': 'Routing Engine', 'jnxContentsL1Index': '1',
                      'jnxContentsSerialNo': 'AACZ0400',
                      'jnxContentsL2Index': '0', 'jnxContentsChassisId': "'singleChassis'",
                      'jnxContentsContainerIndex': '9',
                      'jnxContentsChassisDescr': 'Single Chassis', 'jnxContentsPartNo': '750-031177'}),
                  ('9.1.1.0', {
                      'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxUSBHub.0', 'jnxContentsRevision': '',
                      'jnxContentsInstalled': '0', 'suffix': '9.1.1.0', 'jnxContentsChassisCleiCode': '',
                      'jnxContentsL3Index': '0',
                      'jnxContentsDescr': 'USB Hub', 'jnxContentsL1Index': '1', 'jnxContentsSerialNo': '',
                      'jnxContentsL2Index': '1',
                      'jnxContentsChassisId': "'singleChassis'", 'jnxContentsContainerIndex': '9',
                      'jnxContentsChassisDescr': 'Single Chassis', 'jnxContentsPartNo': ''}),
                  ('9.1.2.0', {
                      'jnxContentsType': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxRCompactFlash.0', 'jnxContentsRevision': '',
                      'jnxContentsInstalled': '0', 'suffix': '9.1.2.0', 'jnxContentsChassisCleiCode': '',
                      'jnxContentsL3Index': '0',
                      'jnxContentsDescr': 'Removable Compact Flash', 'jnxContentsL1Index': '1',
                      'jnxContentsSerialNo': '',
                      'jnxContentsL2Index': '2', 'jnxContentsChassisId': "'singleChassis'",
                      'jnxContentsContainerIndex': '9',
                      'jnxContentsChassisDescr': 'Single Chassis', 'jnxContentsPartNo': ''})]

JUNIPER_IF_CHASSIS = [(3, {'ifChassisLogicalUnit': '0', 'suffix': '3', 'ifChassisChannel': '0', 'ifChassisPic': '0',
                           'ifChassisPort': '0', 'ifChassisPicIndex': '0x08030000', 'ifChassisFpc': '3'}), (4, {
    'ifChassisLogicalUnit': '0', 'suffix': '4', 'ifChassisChannel': '0', 'ifChassisPic': '0', 'ifChassisPort': '0',
    'ifChassisPicIndex': '0x00000000', 'ifChassisFpc': '0'}), (6, {'ifChassisLogicalUnit': '0', 'suffix': '6',
                                                                   'ifChassisChannel': '0', 'ifChassisPic': '0',
                                                                   'ifChassisPort': '0',
                                                                   'ifChassisPicIndex': '0x08010000',
                                                                   'ifChassisFpc': '1'}), (7,
                                                                                           {'ifChassisLogicalUnit': '0',
                                                                                            'suffix': '7',
                                                                                            'ifChassisChannel': '0',
                                                                                            'ifChassisPic': '0',
                                                                                            'ifChassisPort': '0',
                                                                                            'ifChassisPicIndex': '0x00000000',
                                                                                            'ifChassisFpc': '0'}), (8, {
    'ifChassisLogicalUnit': '0', 'suffix': '8', 'ifChassisChannel': '0', 'ifChassisPic': '0', 'ifChassisPort': '0',
    'ifChassisPicIndex': '0x00000000', 'ifChassisFpc': '0'}), (9, {'ifChassisLogicalUnit': '0', 'suffix': '9',
                                                                   'ifChassisChannel': '0', 'ifChassisPic': '0',
                                                                   'ifChassisPort': '0',
                                                                   'ifChassisPicIndex': '0x00000000',
                                                                   'ifChassisFpc': '0'}), (10,
                                                                                           {'ifChassisLogicalUnit': '0',
                                                                                            'suffix': '10',
                                                                                            'ifChassisChannel': '0',
                                                                                            'ifChassisPic': '0',
                                                                                            'ifChassisPort': '0',
                                                                                            'ifChassisPicIndex': '0x00000000',
                                                                                            'ifChassisFpc': '0'}), (11,
                                                                                                                    {
                                                                                                                        'ifChassisLogicalUnit': '0',
                                                                                                                        'suffix': '11',
                                                                                                                        'ifChassisChannel': '0',
                                                                                                                        'ifChassisPic': '0',
                                                                                                                        'ifChassisPort': '0',
                                                                                                                        'ifChassisPicIndex': '0x00000000',
                                                                                                                        'ifChassisFpc': '0'}),
                      (12, {'ifChassisLogicalUnit': '0', 'suffix': '12', 'ifChassisChannel': '0', 'ifChassisPic': '0',
                            'ifChassisPort': '0', 'ifChassisPicIndex': '0x00000000', 'ifChassisFpc': '0'}), (15, {
        'ifChassisLogicalUnit': '1', 'suffix': '15', 'ifChassisChannel': '0', 'ifChassisPic': '0', 'ifChassisPort': '0',
        'ifChassisPicIndex': '0x08030000', 'ifChassisFpc': '3'}), (21, {'ifChassisLogicalUnit': '16385', 'suffix': '21',
                                                                        'ifChassisChannel': '0', 'ifChassisPic': '0',
                                                                        'ifChassisPort': '0',
                                                                        'ifChassisPicIndex': '0x08010000',
                                                                        'ifChassisFpc': '1'}), (22, {
        'ifChassisLogicalUnit': '16386', 'suffix': '22', 'ifChassisChannel': '0', 'ifChassisPic': '0',
        'ifChassisPort': '0', 'ifChassisPicIndex': '0x08010000', 'ifChassisFpc': '1'}), (248, {
        'ifChassisLogicalUnit': '32769', 'suffix': '248', 'ifChassisChannel': '0', 'ifChassisPic': '0',
        'ifChassisPort': '0', 'ifChassisPicIndex': '0x08010000', 'ifChassisFpc': '1'}), (501,
                                                                                         {'ifChassisLogicalUnit': '0',
                                                                                          'suffix': '501',
                                                                                          'ifChassisChannel': '0',
                                                                                          'ifChassisPic': '0',
                                                                                          'ifChassisPort': '0',
                                                                                          'ifChassisPicIndex': '0x00000000',
                                                                                          'ifChassisFpc': '0'}), (502, {
        'ifChassisLogicalUnit': '0', 'suffix': '502', 'ifChassisChannel': '0', 'ifChassisPic': '0',
        'ifChassisPort': '0', 'ifChassisPicIndex': '0x08010000', 'ifChassisFpc': '1'}), (503,
                                                                                         {'ifChassisLogicalUnit': '0',
                                                                                          'suffix': '503',
                                                                                          'ifChassisChannel': '0',
                                                                                          'ifChassisPic': '0',
                                                                                          'ifChassisPort': '0',
                                                                                          'ifChassisPicIndex': '0x08010000',
                                                                                          'ifChassisFpc': '1'}), (504, {
        'ifChassisLogicalUnit': '0', 'suffix': '504', 'ifChassisChannel': '0', 'ifChassisPic': '0',
        'ifChassisPort': '0', 'ifChassisPicIndex': '0x08010000', 'ifChassisFpc': '1'}), (505,
                                                                                         {'ifChassisLogicalUnit': '0',
                                                                                          'suffix': '505',
                                                                                          'ifChassisChannel': '0',
                                                                                          'ifChassisPic': '0',
                                                                                          'ifChassisPort': '0',
                                                                                          'ifChassisPicIndex': '0x08010000',
                                                                                          'ifChassisFpc': '1'}), (506, {
        'ifChassisLogicalUnit': '0', 'suffix': '506', 'ifChassisChannel': '0', 'ifChassisPic': '0',
        'ifChassisPort': '0', 'ifChassisPicIndex': '0x00000000', 'ifChassisFpc': '0'}), (507,
                                                                                         {'ifChassisLogicalUnit': '1',
                                                                                          'suffix': '507',
                                                                                          'ifChassisChannel': '0',
                                                                                          'ifChassisPic': '0',
                                                                                          'ifChassisPort': '0',
                                                                                          'ifChassisPicIndex': '0x00000000',
                                                                                          'ifChassisFpc': '0'}), (508, {
        'ifChassisLogicalUnit': '0', 'suffix': '508', 'ifChassisChannel': '0', 'ifChassisPic': '1',
        'ifChassisPort': '1', 'ifChassisPicIndex': '0x08010100', 'ifChassisFpc': '1'}), (509,
                                                                                         {'ifChassisLogicalUnit': '1',
                                                                                          'suffix': '509',
                                                                                          'ifChassisChannel': '0',
                                                                                          'ifChassisPic': '1',
                                                                                          'ifChassisPort': '1',
                                                                                          'ifChassisPicIndex': '0x08010100',
                                                                                          'ifChassisFpc': '1'}), (510, {
        'ifChassisLogicalUnit': '0', 'suffix': '510', 'ifChassisChannel': '0', 'ifChassisPic': '1',
        'ifChassisPort': '2', 'ifChassisPicIndex': '0x08010100', 'ifChassisFpc': '1'}), (511,
                                                                                         {'ifChassisLogicalUnit': '0',
                                                                                          'suffix': '511',
                                                                                          'ifChassisChannel': '0',
                                                                                          'ifChassisPic': '1',
                                                                                          'ifChassisPort': '3',
                                                                                          'ifChassisPicIndex': '0x08010100',
                                                                                          'ifChassisFpc': '1'}), (512, {
        'ifChassisLogicalUnit': '1', 'suffix': '512', 'ifChassisChannel': '0', 'ifChassisPic': '1',
        'ifChassisPort': '2', 'ifChassisPicIndex': '0x08010100', 'ifChassisFpc': '1'}), (513,
                                                                                         {'ifChassisLogicalUnit': '0',
                                                                                          'suffix': '513',
                                                                                          'ifChassisChannel': '0',
                                                                                          'ifChassisPic': '1',
                                                                                          'ifChassisPort': '4',
                                                                                          'ifChassisPicIndex': '0x08010100',
                                                                                          'ifChassisFpc': '1'}), (514, {
        'ifChassisLogicalUnit': '0', 'suffix': '514', 'ifChassisChannel': '0', 'ifChassisPic': '1',
        'ifChassisPort': '5', 'ifChassisPicIndex': '0x08010100', 'ifChassisFpc': '1'}), (515,
                                                                                         {'ifChassisLogicalUnit': '0',
                                                                                          'suffix': '515',
                                                                                          'ifChassisChannel': '0',
                                                                                          'ifChassisPic': '1',
                                                                                          'ifChassisPort': '6',
                                                                                          'ifChassisPicIndex': '0x08010100',
                                                                                          'ifChassisFpc': '1'}), (516, {
        'ifChassisLogicalUnit': '0', 'suffix': '516', 'ifChassisChannel': '0', 'ifChassisPic': '1',
        'ifChassisPort': '7', 'ifChassisPicIndex': '0x08010100', 'ifChassisFpc': '1'}), (517,
                                                                                         {'ifChassisLogicalUnit': '1',
                                                                                          'suffix': '517',
                                                                                          'ifChassisChannel': '0',
                                                                                          'ifChassisPic': '1',
                                                                                          'ifChassisPort': '3',
                                                                                          'ifChassisPicIndex': '0x08010100',
                                                                                          'ifChassisFpc': '1'}), (518, {
        'ifChassisLogicalUnit': '0', 'suffix': '518', 'ifChassisChannel': '0', 'ifChassisPic': '1',
        'ifChassisPort': '8', 'ifChassisPicIndex': '0x08010100', 'ifChassisFpc': '1'}), (519,
                                                                                         {'ifChassisLogicalUnit': '1',
                                                                                          'suffix': '519',
                                                                                          'ifChassisChannel': '0',
                                                                                          'ifChassisPic': '1',
                                                                                          'ifChassisPort': '4',
                                                                                          'ifChassisPicIndex': '0x08010100',
                                                                                          'ifChassisFpc': '1'}), (520, {
        'ifChassisLogicalUnit': '0', 'suffix': '520', 'ifChassisChannel': '0', 'ifChassisPic': '1',
        'ifChassisPort': '1', 'ifChassisPicIndex': '0x08010100', 'ifChassisFpc': '1'}), (521,
                                                                                         {'ifChassisLogicalUnit': '0',
                                                                                          'suffix': '521',
                                                                                          'ifChassisChannel': '0',
                                                                                          'ifChassisPic': '1',
                                                                                          'ifChassisPort': '1',
                                                                                          'ifChassisPicIndex': '0x08010100',
                                                                                          'ifChassisFpc': '1'}), (522, {
        'ifChassisLogicalUnit': '0', 'suffix': '522', 'ifChassisChannel': '0', 'ifChassisPic': '1',
        'ifChassisPort': '1', 'ifChassisPicIndex': '0x08010100', 'ifChassisFpc': '1'}), (523,
                                                                                         {'ifChassisLogicalUnit': '1',
                                                                                          'suffix': '523',
                                                                                          'ifChassisChannel': '0',
                                                                                          'ifChassisPic': '1',
                                                                                          'ifChassisPort': '5',
                                                                                          'ifChassisPicIndex': '0x08010100',
                                                                                          'ifChassisFpc': '1'}), (524, {
        'ifChassisLogicalUnit': '0', 'suffix': '524', 'ifChassisChannel': '0', 'ifChassisPic': '1',
        'ifChassisPort': '1', 'ifChassisPicIndex': '0x08010100', 'ifChassisFpc': '1'}), (525,
                                                                                         {'ifChassisLogicalUnit': '0',
                                                                                          'suffix': '525',
                                                                                          'ifChassisChannel': '0',
                                                                                          'ifChassisPic': '1',
                                                                                          'ifChassisPort': '1',
                                                                                          'ifChassisPicIndex': '0x08010100',
                                                                                          'ifChassisFpc': '1'}), (526, {
        'ifChassisLogicalUnit': '0', 'suffix': '526', 'ifChassisChannel': '0', 'ifChassisPic': '1',
        'ifChassisPort': '1', 'ifChassisPicIndex': '0x08010100', 'ifChassisFpc': '1'}), (528,
                                                                                         {'ifChassisLogicalUnit': '1',
                                                                                          'suffix': '528',
                                                                                          'ifChassisChannel': '0',
                                                                                          'ifChassisPic': '1',
                                                                                          'ifChassisPort': '7',
                                                                                          'ifChassisPicIndex': '0x08010100',
                                                                                          'ifChassisFpc': '1'}), (529, {
        'ifChassisLogicalUnit': '1', 'suffix': '529', 'ifChassisChannel': '0', 'ifChassisPic': '1',
        'ifChassisPort': '8', 'ifChassisPicIndex': '0x08010100', 'ifChassisFpc': '1'}), (530,
                                                                                         {'ifChassisLogicalUnit': '1',
                                                                                          'suffix': '530',
                                                                                          'ifChassisChannel': '0',
                                                                                          'ifChassisPic': '1',
                                                                                          'ifChassisPort': '1',
                                                                                          'ifChassisPicIndex': '0x08010100',
                                                                                          'ifChassisFpc': '1'}), (531, {
        'ifChassisLogicalUnit': '16384', 'suffix': '531', 'ifChassisChannel': '0', 'ifChassisPic': '1',
        'ifChassisPort': '1', 'ifChassisPicIndex': '0x08010100', 'ifChassisFpc': '1'}), (532,
                                                                                         {'ifChassisLogicalUnit': '41',
                                                                                          'suffix': '532',
                                                                                          'ifChassisChannel': '0',
                                                                                          'ifChassisPic': '0',
                                                                                          'ifChassisPort': '0',
                                                                                          'ifChassisPicIndex': '0x00000000',
                                                                                          'ifChassisFpc': '0'}), (533, {
        'ifChassisLogicalUnit': '42', 'suffix': '533', 'ifChassisChannel': '0', 'ifChassisPic': '0',
        'ifChassisPort': '0', 'ifChassisPicIndex': '0x00000000', 'ifChassisFpc': '0'}), (534,
                                                                                         {'ifChassisLogicalUnit': '0',
                                                                                          'suffix': '534',
                                                                                          'ifChassisChannel': '0',
                                                                                          'ifChassisPic': '0',
                                                                                          'ifChassisPort': '0',
                                                                                          'ifChassisPicIndex': '0x08010000',
                                                                                          'ifChassisFpc': '1'}), (536, {
        'ifChassisLogicalUnit': '1', 'suffix': '536', 'ifChassisChannel': '0', 'ifChassisPic': '0',
        'ifChassisPort': '0', 'ifChassisPicIndex': '0x08010000', 'ifChassisFpc': '1'})]
INTERFACES = [(0, {'ifNumber': '47', 'suffix': '0'}), (3, {'ifType': "'ethernetCsmacd'", 'suffix': '3',
                                                           'ifOutDiscards': '0', 'ifAdminStatus': "'up'",
                                                           'ifMtu': '1514', 'ifInDiscards': '0', 'ifInErrors': '0',
                                                           'ifDescr': 'fxp2', 'ifOperStatus': "'up'",
                                                           'ifOutUcastPkts': '70956', 'ifInOctets': '0',
                                                           'ifLastChange': '1833', 'ifPhysAddress': '00:00:00:00:00:00',
                                                           'ifInUcastPkts': '0',
                                                           'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0',
                                                           'ifIndex': '3', 'ifOutQLen': '0', 'ifSpeed': '0',
                                                           'ifOutNUcastPkts': '0', 'ifOutOctets': '3547100',
                                                           'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (4, {
    'ifType': "'mplsTunnel'", 'suffix': '4', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '1496',
    'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'lsi', 'ifOperStatus': "'up'", 'ifOutUcastPkts': '0',
    'ifInOctets': '0', 'ifLastChange': '0', 'ifPhysAddress': '', 'ifInUcastPkts': '0',
    'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '4', 'ifOutQLen': '0', 'ifSpeed': '0',
    'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (6, {
    'ifType': "'softwareLoopback'", 'suffix': '6', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '2147483647',
    'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'lo0', 'ifOperStatus': "'up'", 'ifOutUcastPkts': '43177',
    'ifInOctets': '2247750', 'ifLastChange': '1840', 'ifPhysAddress': '', 'ifInUcastPkts': '43123',
    'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '6', 'ifOutQLen': '0', 'ifSpeed': '0',
    'ifOutNUcastPkts': '0', 'ifOutOctets': '2250662', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (7, {
    'ifType': "'other'", 'suffix': '7', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '2147483647',
    'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'tap', 'ifOperStatus': "'up'", 'ifOutUcastPkts': '0',
    'ifInOctets': '0', 'ifLastChange': '1849', 'ifPhysAddress': '', 'ifInUcastPkts': '0',
    'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '7', 'ifOutQLen': '0', 'ifSpeed': '0',
    'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (8, {
    'ifType': "'tunnel'", 'suffix': '8', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '2147483647',
    'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'gre', 'ifOperStatus': "'up'", 'ifOutUcastPkts': '0',
    'ifInOctets': '0', 'ifLastChange': '1837', 'ifPhysAddress': '', 'ifInUcastPkts': '0',
    'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '8', 'ifOutQLen': '0', 'ifSpeed': '0',
    'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (9, {
    'ifType': "'tunnel'", 'suffix': '9', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '2147483647',
    'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'ipip', 'ifOperStatus': "'up'", 'ifOutUcastPkts': '0',
    'ifInOctets': '0', 'ifLastChange': '1839', 'ifPhysAddress': '', 'ifInUcastPkts': '0',
    'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '9', 'ifOutQLen': '0', 'ifSpeed': '0',
    'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (10, {
    'ifType': "'tunnel'", 'suffix': '10', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '2147483647',
    'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'pime', 'ifOperStatus': "'up'", 'ifOutUcastPkts': '0',
    'ifInOctets': '0', 'ifLastChange': '1848', 'ifPhysAddress': '', 'ifInUcastPkts': '0',
    'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '10', 'ifOutQLen': '0', 'ifSpeed': '0',
    'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (11, {
    'ifType': "'tunnel'", 'suffix': '11', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '2147483647',
    'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'pimd', 'ifOperStatus': "'up'", 'ifOutUcastPkts': '0',
    'ifInOctets': '0', 'ifLastChange': '1847', 'ifPhysAddress': '', 'ifInUcastPkts': '0',
    'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '11', 'ifOutQLen': '0', 'ifSpeed': '0',
    'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (12, {
    'ifType': "'tunnel'", 'suffix': '12', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '2147483647',
    'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'mtun', 'ifOperStatus': "'up'", 'ifOutUcastPkts': '0',
    'ifInOctets': '0', 'ifLastChange': '1845', 'ifPhysAddress': '', 'ifInUcastPkts': '0',
    'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '12', 'ifOutQLen': '0', 'ifSpeed': '0',
    'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (15, {
    'ifType': "'propVirtual'", 'suffix': '15', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '1514',
    'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'fxp2.0', 'ifOperStatus': "'up'", 'ifOutUcastPkts': '70961',
    'ifInOctets': '0', 'ifLastChange': '1835', 'ifPhysAddress': '00:00:00:00:00:00', 'ifInUcastPkts': '0',
    'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '15', 'ifOutQLen': '0', 'ifSpeed': '0',
    'ifOutNUcastPkts': '0', 'ifOutOctets': '2553984', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (21, {
    'ifType': "'softwareLoopback'", 'suffix': '21', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'",
    'ifMtu': '2147483647', 'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'lo0.16384', 'ifOperStatus': "'up'",
    'ifOutUcastPkts': '0', 'ifInOctets': '0', 'ifLastChange': '1841', 'ifPhysAddress': '', 'ifInUcastPkts': '0',
    'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '21', 'ifOutQLen': '0', 'ifSpeed': '0',
    'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (22, {
    'ifType': "'softwareLoopback'", 'suffix': '22', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'",
    'ifMtu': '2147483647', 'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'lo0.16385', 'ifOperStatus': "'up'",
    'ifOutUcastPkts': '43181', 'ifInOctets': '2247958', 'ifLastChange': '1842', 'ifPhysAddress': '',
    'ifInUcastPkts': '43125', 'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '22',
    'ifOutQLen': '0', 'ifSpeed': '0', 'ifOutNUcastPkts': '0', 'ifOutOctets': '2250766', 'ifInUnknownProtos': '0',
    'ifInNUcastPkts': '0'}), (248, {'ifType': "'softwareLoopback'", 'suffix': '248', 'ifOutDiscards': '0',
                                    'ifAdminStatus': "'up'", 'ifMtu': '0', 'ifInDiscards': '0', 'ifInErrors': '0',
                                    'ifDescr': 'lo0.32768', 'ifOperStatus': "'up'", 'ifOutUcastPkts': '0',
                                    'ifInOctets': '0', 'ifLastChange': '1843', 'ifPhysAddress': '',
                                    'ifInUcastPkts': '0', 'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0',
                                    'ifIndex': '248', 'ifOutQLen': '0', 'ifSpeed': '0', 'ifOutNUcastPkts': '0',
                                    'ifOutOctets': '0', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (501, {
    'ifType': "'other'", 'suffix': '501', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '1514',
    'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'irb', 'ifOperStatus': "'up'", 'ifOutUcastPkts': '0',
    'ifInOctets': '0', 'ifLastChange': '4597', 'ifPhysAddress': '2c:21:72:c6:aa:30', 'ifInUcastPkts': '0',
    'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '501', 'ifOutQLen': '0', 'ifSpeed': '0',
    'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (502, {
    'ifType': "'other'", 'suffix': '502', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '1532',
    'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'pp0', 'ifOperStatus': "'up'", 'ifOutUcastPkts': '0',
    'ifInOctets': '0', 'ifLastChange': '4593', 'ifPhysAddress': '', 'ifInUcastPkts': '0',
    'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '502', 'ifOutQLen': '0', 'ifSpeed': '0',
    'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (503, {
    'ifType': "'other'", 'suffix': '503', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '9192',
    'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'st0', 'ifOperStatus': "'up'", 'ifOutUcastPkts': '0',
    'ifInOctets': '0', 'ifLastChange': '4611', 'ifPhysAddress': '', 'ifInUcastPkts': '0',
    'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '503', 'ifOutQLen': '0', 'ifSpeed': '0',
    'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (504, {
    'ifType': "'tunnel'", 'suffix': '504', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '2147483647',
    'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'ppd0', 'ifOperStatus': "'up'", 'ifOutUcastPkts': '0',
    'ifInOctets': '0', 'ifLastChange': '4615', 'ifPhysAddress': '', 'ifInUcastPkts': '0',
    'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '504', 'ifOutQLen': '0',
    'ifSpeed': '800000000', 'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0',
    'ifInNUcastPkts': '0'}), (505,
                              {'ifType': "'tunnel'", 'suffix': '505', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'",
                               'ifMtu': '2147483647', 'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'ppe0',
                               'ifOperStatus': "'up'", 'ifOutUcastPkts': '0', 'ifInOctets': '0', 'ifLastChange': '4636',
                               'ifPhysAddress': '', 'ifInUcastPkts': '0', 'ifSpecific': 'SNMPv2-SMI::zeroDotZero',
                               'ifOutErrors': '0', 'ifIndex': '505', 'ifOutQLen': '0', 'ifSpeed': '800000000',
                               'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0',
                               'ifInNUcastPkts': '0'}), (506, {'ifType': "'ethernetCsmacd'", 'suffix': '506',
                                                               'ifOutDiscards': '0', 'ifAdminStatus': "'up'",
                                                               'ifMtu': '1518', 'ifInDiscards': '0', 'ifInErrors': '0',
                                                               'ifDescr': 'vlan', 'ifOperStatus': "'up'",
                                                               'ifOutUcastPkts': '2', 'ifInOctets': '0',
                                                               'ifLastChange': '5483',
                                                               'ifPhysAddress': '2c:21:72:c6:a9:88',
                                                               'ifInUcastPkts': '0',
                                                               'ifSpecific': 'SNMPv2-SMI::zeroDotZero',
                                                               'ifOutErrors': '0', 'ifIndex': '506', 'ifOutQLen': '0',
                                                               'ifSpeed': '1000000000', 'ifOutNUcastPkts': '0',
                                                               'ifOutOctets': '128', 'ifInUnknownProtos': '0',
                                                               'ifInNUcastPkts': '0'}), (507, {'ifType': "'l2vlan'",
                                                                                               'suffix': '507',
                                                                                               'ifOutDiscards': '0',
                                                                                               'ifAdminStatus': "'up'",
                                                                                               'ifMtu': '1500',
                                                                                               'ifInDiscards': '0',
                                                                                               'ifInErrors': '0',
                                                                                               'ifDescr': 'vlan.0',
                                                                                               'ifOperStatus': "'up'",
                                                                                               'ifOutUcastPkts': '2',
                                                                                               'ifInOctets': '0',
                                                                                               'ifLastChange': '6169',
                                                                                               'ifPhysAddress': '2c:21:72:c6:a9:88',
                                                                                               'ifInUcastPkts': '0',
                                                                                               'ifSpecific': 'SNMPv2-SMI::zeroDotZero',
                                                                                               'ifOutErrors': '0',
                                                                                               'ifIndex': '507',
                                                                                               'ifOutQLen': '0',
                                                                                               'ifSpeed': '0',
                                                                                               'ifOutNUcastPkts': '0',
                                                                                               'ifOutOctets': '168',
                                                                                               'ifInUnknownProtos': '0',
                                                                                               'ifInNUcastPkts': '0'}),
              (508, {'ifType': "'ethernetCsmacd'", 'suffix': '508', 'ifOutDiscards': '0', 'ifAdminStatus': "'down'",
                     'ifMtu': '1514', 'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'ge-0/0/0',
                     'ifOperStatus': "'down'", 'ifOutUcastPkts': '0', 'ifInOctets': '0', 'ifLastChange': '5538',
                     'ifPhysAddress': '2c:21:72:c6:a9:80', 'ifInUcastPkts': '0',
                     'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '508', 'ifOutQLen': '0',
                     'ifSpeed': '1000000000', 'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0',
                     'ifInNUcastPkts': '0'}), (509, {'ifType': "'propVirtual'", 'suffix': '509', 'ifOutDiscards': '0',
                                                     'ifAdminStatus': "'up'", 'ifMtu': '1514', 'ifInDiscards': '0',
                                                     'ifInErrors': '0', 'ifDescr': 'ge-0/0/0.0',
                                                     'ifOperStatus': "'lowerLayerDown'", 'ifOutUcastPkts': '0',
                                                     'ifInOctets': '0', 'ifLastChange': '5544',
                                                     'ifPhysAddress': '2c:21:72:c6:a9:80', 'ifInUcastPkts': '0',
                                                     'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0',
                                                     'ifIndex': '509', 'ifOutQLen': '0', 'ifSpeed': '1000000000',
                                                     'ifOutNUcastPkts': '0', 'ifOutOctets': '0',
                                                     'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (510, {
        'ifType': "'ethernetCsmacd'", 'suffix': '510', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '1514',
        'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'ge-0/0/1', 'ifOperStatus': "'down'", 'ifOutUcastPkts': '0',
        'ifInOctets': '0', 'ifLastChange': '5542', 'ifPhysAddress': '2c:21:72:c6:a9:81', 'ifInUcastPkts': '0',
        'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '510', 'ifOutQLen': '0',
        'ifSpeed': '1000000000', 'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0',
        'ifInNUcastPkts': '0'}), (511, {'ifType': "'ethernetCsmacd'", 'suffix': '511', 'ifOutDiscards': '0',
                                        'ifAdminStatus': "'down'", 'ifMtu': '1514', 'ifInDiscards': '0',
                                        'ifInErrors': '0', 'ifDescr': 'ge-0/0/2', 'ifOperStatus': "'down'",
                                        'ifOutUcastPkts': '0', 'ifInOctets': '0', 'ifLastChange': '5548',
                                        'ifPhysAddress': '2c:21:72:c6:a9:82', 'ifInUcastPkts': '0',
                                        'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '511',
                                        'ifOutQLen': '0', 'ifSpeed': '1000000000', 'ifOutNUcastPkts': '0',
                                        'ifOutOctets': '0', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (512, {
        'ifType': "'propVirtual'", 'suffix': '512', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '1514',
        'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'ge-0/0/1.0', 'ifOperStatus': "'lowerLayerDown'",
        'ifOutUcastPkts': '0', 'ifInOctets': '0', 'ifLastChange': '5556', 'ifPhysAddress': '2c:21:72:c6:a9:81',
        'ifInUcastPkts': '0', 'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '512',
        'ifOutQLen': '0', 'ifSpeed': '1000000000', 'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0',
        'ifInNUcastPkts': '0'}), (513, {'ifType': "'ethernetCsmacd'", 'suffix': '513', 'ifOutDiscards': '0',
                                        'ifAdminStatus': "'up'", 'ifMtu': '1514', 'ifInDiscards': '0',
                                        'ifInErrors': '0', 'ifDescr': 'ge-0/0/3', 'ifOperStatus': "'up'",
                                        'ifOutUcastPkts': '16219', 'ifInOctets': '11147188', 'ifLastChange': '6067',
                                        'ifPhysAddress': '2c:21:72:c6:a9:83', 'ifInUcastPkts': '15724',
                                        'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '513',
                                        'ifOutQLen': '0', 'ifSpeed': '1000000000', 'ifOutNUcastPkts': '1',
                                        'ifOutOctets': '2103805', 'ifInUnknownProtos': '0',
                                        'ifInNUcastPkts': '147523'}), (514,
                                                                       {'ifType': "'ethernetCsmacd'", 'suffix': '514',
                                                                        'ifOutDiscards': '0', 'ifAdminStatus': "'down'",
                                                                        'ifMtu': '1514', 'ifInDiscards': '0',
                                                                        'ifInErrors': '0', 'ifDescr': 'ge-0/0/4',
                                                                        'ifOperStatus': "'down'", 'ifOutUcastPkts': '0',
                                                                        'ifInOctets': '0', 'ifLastChange': '5560',
                                                                        'ifPhysAddress': '2c:21:72:c6:a9:84',
                                                                        'ifInUcastPkts': '0',
                                                                        'ifSpecific': 'SNMPv2-SMI::zeroDotZero',
                                                                        'ifOutErrors': '0', 'ifIndex': '514',
                                                                        'ifOutQLen': '0', 'ifSpeed': '1000000000',
                                                                        'ifOutNUcastPkts': '0', 'ifOutOctets': '0',
                                                                        'ifInUnknownProtos': '0',
                                                                        'ifInNUcastPkts': '0'}), (515, {
        'ifType': "'ethernetCsmacd'", 'suffix': '515', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '1514',
        'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'ge-0/0/5', 'ifOperStatus': "'down'", 'ifOutUcastPkts': '0',
        'ifInOctets': '0', 'ifLastChange': '5568', 'ifPhysAddress': '2c:21:72:c6:a9:85', 'ifInUcastPkts': '0',
        'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '515', 'ifOutQLen': '0',
        'ifSpeed': '1000000000', 'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0',
        'ifInNUcastPkts': '0'}), (516, {'ifType': "'ethernetCsmacd'", 'suffix': '516', 'ifOutDiscards': '0',
                                        'ifAdminStatus': "'down'", 'ifMtu': '1514', 'ifInDiscards': '0',
                                        'ifInErrors': '0', 'ifDescr': 'ge-0/0/6', 'ifOperStatus': "'down'",
                                        'ifOutUcastPkts': '0', 'ifInOctets': '0', 'ifLastChange': '5576',
                                        'ifPhysAddress': '2c:21:72:c6:a9:86', 'ifInUcastPkts': '0',
                                        'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '516',
                                        'ifOutQLen': '0', 'ifSpeed': '1000000000', 'ifOutNUcastPkts': '0',
                                        'ifOutOctets': '0', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (517, {
        'ifType': "'propVirtual'", 'suffix': '517', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '1514',
        'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'ge-0/0/2.0', 'ifOperStatus': "'lowerLayerDown'",
        'ifOutUcastPkts': '0', 'ifInOctets': '0', 'ifLastChange': '5571', 'ifPhysAddress': '2c:21:72:c6:a9:82',
        'ifInUcastPkts': '0', 'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '517',
        'ifOutQLen': '0', 'ifSpeed': '1000000000', 'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0',
        'ifInNUcastPkts': '0'}), (518, {'ifType': "'ethernetCsmacd'", 'suffix': '518', 'ifOutDiscards': '0',
                                        'ifAdminStatus': "'up'", 'ifMtu': '1514', 'ifInDiscards': '0',
                                        'ifInErrors': '0', 'ifDescr': 'ge-0/0/7', 'ifOperStatus': "'up'",
                                        'ifOutUcastPkts': '0', 'ifInOctets': '0', 'ifLastChange': '6167',
                                        'ifPhysAddress': '2c:21:72:c6:a9:87', 'ifInUcastPkts': '0',
                                        'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '518',
                                        'ifOutQLen': '0', 'ifSpeed': '1000000000', 'ifOutNUcastPkts': '37531',
                                        'ifOutOctets': '4351676', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (
                  519, {'ifType': "'propVirtual'", 'suffix': '519', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'",
                        'ifMtu': '1500', 'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'ge-0/0/3.0',
                        'ifOperStatus': "'up'", 'ifOutUcastPkts': '16237', 'ifInOctets': '11148476',
                        'ifLastChange': '6067',
                        'ifPhysAddress': '2c:21:72:c6:a9:83', 'ifInUcastPkts': '160848',
                        'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '519', 'ifOutQLen': '0',
                        'ifSpeed': '1000000000', 'ifOutNUcastPkts': '0', 'ifOutOctets': '1468223',
                        'ifInUnknownProtos': '0',
                        'ifInNUcastPkts': '0'}), (520, {'ifType': "'other'", 'suffix': '520', 'ifOutDiscards': '0',
                                                        'ifAdminStatus': "'up'", 'ifMtu': '9192', 'ifInDiscards': '0',
                                                        'ifInErrors': '0', 'ifDescr': 'sp-0/0/0',
                                                        'ifOperStatus': "'up'",
                                                        'ifOutUcastPkts': '0', 'ifInOctets': '0',
                                                        'ifLastChange': '5766',
                                                        'ifPhysAddress': '', 'ifInUcastPkts': '0',
                                                        'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0',
                                                        'ifIndex': '520', 'ifOutQLen': '0', 'ifSpeed': '800000000',
                                                        'ifOutNUcastPkts': '0', 'ifOutOctets': '0',
                                                        'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (521, {
        'ifType': "'tunnel'", 'suffix': '521', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '2147483647',
        'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'gr-0/0/0', 'ifOperStatus': "'up'", 'ifOutUcastPkts': '0',
        'ifInOctets': '0', 'ifLastChange': '5597', 'ifPhysAddress': '', 'ifInUcastPkts': '0',
        'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '521', 'ifOutQLen': '0',
        'ifSpeed': '800000000', 'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0',
        'ifInNUcastPkts': '0'}), (522,
                                  {'ifType': "'tunnel'", 'suffix': '522', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'",
                                   'ifMtu': '2147483647', 'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'ip-0/0/0',
                                   'ifOperStatus': "'up'", 'ifOutUcastPkts': '0', 'ifInOctets': '0',
                                   'ifLastChange': '5600', 'ifPhysAddress': '', 'ifInUcastPkts': '0',
                                   'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '522',
                                   'ifOutQLen': '0', 'ifSpeed': '800000000', 'ifOutNUcastPkts': '0', 'ifOutOctets': '0',
                                   'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (523, {'ifType': "'propVirtual'",
                                                                                             'suffix': '523',
                                                                                             'ifOutDiscards': '0',
                                                                                             'ifAdminStatus': "'up'",
                                                                                             'ifMtu': '1514',
                                                                                             'ifInDiscards': '0',
                                                                                             'ifInErrors': '0',
                                                                                             'ifDescr': 'ge-0/0/4.0',
                                                                                             'ifOperStatus': "'lowerLayerDown'",
                                                                                             'ifOutUcastPkts': '0',
                                                                                             'ifInOctets': '0',
                                                                                             'ifLastChange': '5618',
                                                                                             'ifPhysAddress': '2c:21:72:c6:a9:84',
                                                                                             'ifInUcastPkts': '0',
                                                                                             'ifSpecific': 'SNMPv2-SMI::zeroDotZero',
                                                                                             'ifOutErrors': '0',
                                                                                             'ifIndex': '523',
                                                                                             'ifOutQLen': '0',
                                                                                             'ifSpeed': '1000000000',
                                                                                             'ifOutNUcastPkts': '0',
                                                                                             'ifOutOctets': '0',
                                                                                             'ifInUnknownProtos': '0',
                                                                                             'ifInNUcastPkts': '0'}), (
                  524,
                  {'ifType': "'pppMultilinkBundle'", 'suffix': '524', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'",
                   'ifMtu': '1504', 'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'lsq-0/0/0',
                   'ifOperStatus': "'up'", 'ifOutUcastPkts': '0', 'ifInOctets': '0', 'ifLastChange': '5766',
                   'ifPhysAddress': '', 'ifInUcastPkts': '0', 'ifSpecific': 'SNMPv2-SMI::zeroDotZero',
                   'ifOutErrors': '0', 'ifIndex': '524', 'ifOutQLen': '0', 'ifSpeed': '622080000',
                   'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (525,
                                                                                                                   {
                                                                                                                       'ifType': "'tunnel'",
                                                                                                                       'suffix': '525',
                                                                                                                       'ifOutDiscards': '0',
                                                                                                                       'ifAdminStatus': "'up'",
                                                                                                                       'ifMtu': '2147483647',
                                                                                                                       'ifInDiscards': '0',
                                                                                                                       'ifInErrors': '0',
                                                                                                                       'ifDescr': 'mt-0/0/0',
                                                                                                                       'ifOperStatus': "'up'",
                                                                                                                       'ifOutUcastPkts': '0',
                                                                                                                       'ifInOctets': '0',
                                                                                                                       'ifLastChange': '5766',
                                                                                                                       'ifPhysAddress': '',
                                                                                                                       'ifInUcastPkts': '0',
                                                                                                                       'ifSpecific': 'SNMPv2-SMI::zeroDotZero',
                                                                                                                       'ifOutErrors': '0',
                                                                                                                       'ifIndex': '525',
                                                                                                                       'ifOutQLen': '0',
                                                                                                                       'ifSpeed': '800000000',
                                                                                                                       'ifOutNUcastPkts': '0',
                                                                                                                       'ifOutOctets': '0',
                                                                                                                       'ifInUnknownProtos': '0',
                                                                                                                       'ifInNUcastPkts': '0'}),
              (526, {'ifType': "'tunnel'", 'suffix': '526', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'",
                     'ifMtu': '2147483647', 'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'lt-0/0/0',
                     'ifOperStatus': "'up'", 'ifOutUcastPkts': '0', 'ifInOctets': '0', 'ifLastChange': '5613',
                     'ifPhysAddress': '2c:21:72:c6:a9:80', 'ifInUcastPkts': '0',
                     'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '526', 'ifOutQLen': '0',
                     'ifSpeed': '800000000', 'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0',
                     'ifInNUcastPkts': '0'}), (528, {'ifType': "'propVirtual'", 'suffix': '528', 'ifOutDiscards': '0',
                                                     'ifAdminStatus': "'up'", 'ifMtu': '1514', 'ifInDiscards': '0',
                                                     'ifInErrors': '0', 'ifDescr': 'ge-0/0/6.0',
                                                     'ifOperStatus': "'lowerLayerDown'", 'ifOutUcastPkts': '0',
                                                     'ifInOctets': '0', 'ifLastChange': '5621',
                                                     'ifPhysAddress': '2c:21:72:c6:a9:86', 'ifInUcastPkts': '0',
                                                     'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0',
                                                     'ifIndex': '528', 'ifOutQLen': '0', 'ifSpeed': '1000000000',
                                                     'ifOutNUcastPkts': '0', 'ifOutOctets': '0',
                                                     'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (529, {
        'ifType': "'propVirtual'", 'suffix': '529', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '1514',
        'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'ge-0/0/7.0', 'ifOperStatus': "'up'",
        'ifOutUcastPkts': '75049', 'ifInOctets': '0', 'ifLastChange': '6167', 'ifPhysAddress': '2c:21:72:c6:a9:87',
        'ifInUcastPkts': '0', 'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '529',
        'ifOutQLen': '0', 'ifSpeed': '1000000000', 'ifOutNUcastPkts': '0', 'ifOutOctets': '5102176',
        'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (530, {'ifType': "'propVirtual'", 'suffix': '530',
                                                                  'ifOutDiscards': '0', 'ifAdminStatus': "'up'",
                                                                  'ifMtu': '9192', 'ifInDiscards': '0',
                                                                  'ifInErrors': '0', 'ifDescr': 'sp-0/0/0.0',
                                                                  'ifOperStatus': "'up'", 'ifOutUcastPkts': '0',
                                                                  'ifInOctets': '0', 'ifLastChange': '5766',
                                                                  'ifPhysAddress': '', 'ifInUcastPkts': '0',
                                                                  'ifSpecific': 'SNMPv2-SMI::zeroDotZero',
                                                                  'ifOutErrors': '0', 'ifIndex': '530',
                                                                  'ifOutQLen': '0', 'ifSpeed': '800000000',
                                                                  'ifOutNUcastPkts': '0', 'ifOutOctets': '0',
                                                                  'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}), (
                  531, {'ifType': "'propVirtual'", 'suffix': '531', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'",
                        'ifMtu': '9192', 'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'sp-0/0/0.16383',
                        'ifOperStatus': "'up'", 'ifOutUcastPkts': '0', 'ifInOctets': '0', 'ifLastChange': '5766',
                        'ifPhysAddress': '', 'ifInUcastPkts': '0', 'ifSpecific': 'SNMPv2-SMI::zeroDotZero',
                        'ifOutErrors': '0', 'ifIndex': '531', 'ifOutQLen': '0', 'ifSpeed': '800000000',
                        'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0', 'ifInNUcastPkts': '0'}),
              (532,
               {
                   'ifType': "'l2vlan'",
                   'suffix': '532',
                   'ifOutDiscards': '0',
                   'ifAdminStatus': "'up'",
                   'ifMtu': '1500',
                   'ifInDiscards': '0',
                   'ifInErrors': '0',
                   'ifDescr': 'vlan.40',
                   'ifOperStatus': "'down'",
                   'ifOutUcastPkts': '0',
                   'ifInOctets': '0',
                   'ifLastChange': '4660',
                   'ifPhysAddress': '2c:21:72:c6:a9:88',
                   'ifInUcastPkts': '0',
                   'ifSpecific': 'SNMPv2-SMI::zeroDotZero',
                   'ifOutErrors': '0',
                   'ifIndex': '532',
                   'ifOutQLen': '0',
                   'ifSpeed': '0',
                   'ifOutNUcastPkts': '0',
                   'ifOutOctets': '0',
                   'ifInUnknownProtos': '0',
                   'ifInNUcastPkts': '0'}),
              (533,
               {'ifType': "'l2vlan'", 'suffix': '533', 'ifOutDiscards': '0', 'ifAdminStatus': "'up'", 'ifMtu': '1500',
                'ifInDiscards': '0', 'ifInErrors': '0', 'ifDescr': 'vlan.41', 'ifOperStatus': "'down'",
                'ifOutUcastPkts': '0', 'ifInOctets': '0', 'ifLastChange': '4669', 'ifPhysAddress': '2c:21:72:c6:a9:88',
                'ifInUcastPkts': '0', 'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0', 'ifIndex': '533',
                'ifOutQLen': '0', 'ifSpeed': '0', 'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0',
                'ifInNUcastPkts': '0'}), (534, {'ifType': "'ieee8023adLag'", 'suffix': '534', 'ifOutDiscards': '0',
                                                'ifAdminStatus': "'up'", 'ifMtu': '1514', 'ifInDiscards': '0',
                                                'ifInErrors': '0', 'ifDescr': 'ae0', 'ifOperStatus': "'down'",
                                                'ifOutUcastPkts': '0', 'ifInOctets': '0', 'ifLastChange': '4582',
                                                'ifPhysAddress': '2c:21:72:c6:aa:00', 'ifInUcastPkts': '0',
                                                'ifSpecific': 'SNMPv2-SMI::zeroDotZero', 'ifOutErrors': '0',
                                                'ifIndex': '534', 'ifOutQLen': '0', 'ifSpeed': '0',
                                                'ifOutNUcastPkts': '0', 'ifOutOctets': '0', 'ifInUnknownProtos': '0',
                                                'ifInNUcastPkts': '0'}), (536,
                                                                          {'ifType': "'ieee8023adLag'", 'suffix': '536',
                                                                           'ifOutDiscards': '0',
                                                                           'ifAdminStatus': "'up'", 'ifMtu': '1514',
                                                                           'ifInDiscards': '0', 'ifInErrors': '0',
                                                                           'ifDescr': 'ae0.0', 'ifOperStatus': "'down'",
                                                                           'ifOutUcastPkts': '0', 'ifInOctets': '0',
                                                                           'ifLastChange': '4606',
                                                                           'ifPhysAddress': '2c:21:72:c6:aa:00',
                                                                           'ifInUcastPkts': '0',
                                                                           'ifSpecific': 'SNMPv2-SMI::zeroDotZero',
                                                                           'ifOutErrors': '0', 'ifIndex': '536',
                                                                           'ifOutQLen': '0', 'ifSpeed': '0',
                                                                           'ifOutNUcastPkts': '0', 'ifOutOctets': '0',
                                                                           'ifInUnknownProtos': '0',
                                                                           'ifInNUcastPkts': '0'})]
IP_ADDR_TABLE = [('10.0.0.1', {'ipAdEntAddr': '10.0.0.1', 'ipAdEntIfIndex': '22', 'suffix': '10.0.0.1',
                               'ipAdEntNetMask': '255.255.255.255', 'ipAdEntBcastAddr': '1',
                               'ipAdEntReasmMaxSize': '65535'}), ('10.0.0.6',
                                                                  {'ipAdEntAddr': '10.0.0.6', 'ipAdEntIfIndex': '531',
                                                                   'suffix': '10.0.0.6',
                                                                   'ipAdEntNetMask': '255.255.255.255',
                                                                   'ipAdEntBcastAddr': '1',
                                                                   'ipAdEntReasmMaxSize': '65535'}), ('10.0.0.10', {
    'ipAdEntAddr': '10.0.0.10', 'ipAdEntIfIndex': '532', 'suffix': '10.0.0.10', 'ipAdEntNetMask': '255.255.255.0',
    'ipAdEntBcastAddr': '1', 'ipAdEntReasmMaxSize': '65535'}), ('10.0.0.16',
                                                                {'ipAdEntAddr': '10.0.0.16', 'ipAdEntIfIndex': '22',
                                                                 'suffix': '10.0.0.16',
                                                                 'ipAdEntNetMask': '255.255.255.255',
                                                                 'ipAdEntBcastAddr': '1',
                                                                 'ipAdEntReasmMaxSize': '65535'}), ('127.0.0.1', {
    'ipAdEntAddr': '127.0.0.1', 'ipAdEntIfIndex': '21', 'suffix': '127.0.0.1', 'ipAdEntNetMask': '255.255.255.255',
    'ipAdEntBcastAddr': '1', 'ipAdEntReasmMaxSize': '65535'}), ('128.0.0.1',
                                                                {'ipAdEntAddr': '128.0.0.1', 'ipAdEntIfIndex': '22',
                                                                 'suffix': '128.0.0.1',
                                                                 'ipAdEntNetMask': '255.255.255.255',
                                                                 'ipAdEntBcastAddr': '1',
                                                                 'ipAdEntReasmMaxSize': '65535'}), ('128.0.0.4', {
    'ipAdEntAddr': '128.0.0.4', 'ipAdEntIfIndex': '22', 'suffix': '128.0.0.4', 'ipAdEntNetMask': '255.255.255.255',
    'ipAdEntBcastAddr': '1', 'ipAdEntReasmMaxSize': '65535'}), ('128.0.0.6',
                                                                {'ipAdEntAddr': '128.0.0.6', 'ipAdEntIfIndex': '531',
                                                                 'suffix': '128.0.0.6',
                                                                 'ipAdEntNetMask': '255.255.255.255',
                                                                 'ipAdEntBcastAddr': '1',
                                                                 'ipAdEntReasmMaxSize': '65535'}), ('128.0.1.16', {
    'ipAdEntAddr': '128.0.1.16', 'ipAdEntIfIndex': '22', 'suffix': '128.0.1.16', 'ipAdEntNetMask': '255.255.255.255',
    'ipAdEntBcastAddr': '1', 'ipAdEntReasmMaxSize': '65535'}), ('192.168.1.1',
                                                                {'ipAdEntAddr': '192.168.1.1', 'ipAdEntIfIndex': '507',
                                                                 'suffix': '192.168.1.1',
                                                                 'ipAdEntNetMask': '255.255.255.0',
                                                                 'ipAdEntBcastAddr': '1',
                                                                 'ipAdEntReasmMaxSize': '65535'}), ('192.168.28.150', {
    'ipAdEntAddr': '192.168.28.150', 'ipAdEntIfIndex': '519', 'suffix': '192.168.28.150',
    'ipAdEntNetMask': '255.255.255.0', 'ipAdEntBcastAddr': '1', 'ipAdEntReasmMaxSize': '65535'}), ('192.168.41.250', {
    'ipAdEntAddr': '192.168.41.250', 'ipAdEntIfIndex': '533', 'suffix': '192.168.41.250',
    'ipAdEntNetMask': '255.255.255.0', 'ipAdEntBcastAddr': '1', 'ipAdEntReasmMaxSize': '65535'})]
IF_DUPLEX = [(508, {'dot3StatsDuplexStatus': "'fullDuplex'", 'suffix': '508'}),
             (509, {'dot3StatsDuplexStatus': "'fullDuplex'", 'suffix': '509'}),
             (510, {'dot3StatsDuplexStatus': "'fullDuplex'", 'suffix': '510'}),
             (511, {'dot3StatsDuplexStatus': "'fullDuplex'", 'suffix': '511'}),
             (512, {'dot3StatsDuplexStatus': "'fullDuplex'", 'suffix': '512'}),
             (513, {'dot3StatsDuplexStatus': "'fullDuplex'", 'suffix': '513'}),
             (514, {'dot3StatsDuplexStatus': "'fullDuplex'", 'suffix': '514'}),
             (515, {'dot3StatsDuplexStatus': "'fullDuplex'", 'suffix': '515'}),
             (516, {'dot3StatsDuplexStatus': "'fullDuplex'", 'suffix': '516'}),
             (517, {'dot3StatsDuplexStatus': "'fullDuplex'", 'suffix': '517'}),
             (518, {'dot3StatsDuplexStatus': "'fullDuplex'", 'suffix': '518'}),
             (519, {'dot3StatsDuplexStatus': "'fullDuplex'", 'suffix': '519'}),
             (523, {'dot3StatsDuplexStatus': "'fullDuplex'", 'suffix': '523'}),
             (528, {'dot3StatsDuplexStatus': "'fullDuplex'", 'suffix': '528'}),
             (529, {'dot3StatsDuplexStatus': "'fullDuplex'", 'suffix': '529'})]
SYSTEM = [(0, {'sysName': '', 'sysObjectID': 'JUNIPER-CHASSIS-DEFINES-MIB::jnxProductNameSRX220', 'suffix': '0',
               'sysLocation': '', 'sysServices': '4', 'sysUpTime': '7245204',
               'sysDescr': 'Juniper Networks, Inc. srx220h-poe internet router, kernel JUNOS 12.1R6.5 #0: 2013-04-18 05:12:18 UTC     builder@rementh.juniper.net:/volume/build/junos/12.1/release/12.1R6.5/obj-octeon/junos/bsd/kernels/JSRXNLE/kernel Build date: 2013-04-18 06:40:26 UT',
               'sysContact': ''})]
LAG_MIB_PORTS = []

MIB_DATA_MAP = {'JUNIPER-MIB::jnxContainersTable': CONTAINER_TABLE,
                'JUNIPER-MIB::jnxContentsTable': CONTENTS_TABLE,
                'SNMPv2-MIB::system': SYSTEM,
                'JUNIPER-IF-MIB::ifChassisTable': JUNIPER_IF_CHASSIS,
                'IF-MIB::interfaces': INTERFACES,
                'IP-MIB::ipAddrTable': IP_ADDR_TABLE,
                'IEEE8023-LAG-MIB::dot3adAggPortAttachedAggID': LAG_MIB_PORTS,
                'EtherLike-MIB::dot3StatsDuplexStatus': IF_DUPLEX}
